name = "allsquared-website"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "allsquared-blog"
database_id = "57ad98e1-4ffa-4890-9985-608c9f92c44a"
